### ISSUE TITLE
The player can draw a path beyond the bounds of the navmesh

### ISSUE THREAD

**Issue by LachlanRMMorrow** [LachlanRMMorrow/Bullet-Ballet-Unity-Project#15]
## Bug occurring in Build. Not Tested in Editor.

**Expected Result:** _The player cannot draw a path over areas that are not on the baked level navmesh._

**Actual Result:** _The player can draw a path over areas that are not on the baked level navmesh._

**Comment by AddisonStewart** [comment]
The Waypoint system currently cant go through walls, so if all areas are walled off the player shouldn't be able to draw outside walkable areas.

Invisible walls would solve this issue if we wanted open areas

**Comment by LachlanRMMorrow** [comment]
In that case I'll just put in some invisible walls.

**Comment by LachlanRMMorrow** [comment]
Problem solved with the invisible wall workaround.
