### ISSUE TITLE
Enemies frequently do not see the player when they are behind or next to them

### ISSUE THREAD

**Issue by JCRendingRaven** [LachlanRMMorrow/Bullet-Ballet-Unity-Project#2]
## Bug occuring in Editor. Not Tested in Build.

**Expected Result:** _Enemies should see the player when they are behind or next to them._

**Actual Result:** _Enemies frequently do not see the player when they are behind or next to them._

**Comment by LachlanRMMorrow** [comment]
Issue Solved. Good job James.
