### ISSUE TITLE
Fog is always on in the room where the player starts

### ISSUE THREAD

**Issue by LachlanRMMorrow** [LachlanRMMorrow/Bullet-Ballet-Unity-Project#27]
## Bug occurring in Editor. Not Tested in Build.

**Expected Result:** _When the level starts, fog should be off in the room where the player starts and adjacent rooms._

**Actual Result:** _When the level starts, fog is on in the room where the player starts as though they were not in the room._

**Comment by jamesy012** [comment]
Can you give us a scene where this is happening?

**Comment by LachlanRMMorrow** [comment]
Seems to be fixed for now... I'll reopen this if I see it happening again.
