### ISSUE TITLE
When fog is revealed in adjacent rooms, enemies are not

### ISSUE THREAD

**Issue by LachlanRMMorrow** [LachlanRMMorrow/Bullet-Ballet-Unity-Project#28]
## Bug occurring in Editor. Not Tested in Build.

**Expected Result:** _Fog should be off, and enemies should be visible in the room the player occupies as well as adjacent rooms._

**Actual Result:** _Fog is off in the current and adjacent rooms, but enemies are still invisible in adjacent rooms._

**Comment by JCRendingRaven** [comment]
this error is occurring in James Prototype 1, cabin_inside and server_building and is likely occurring in other levels

**Comment by LachlanRMMorrow** [comment]
Seems to be fixed. Thanks James.
