### ISSUE TITLE
The player can begin playing a level before the camera has finished panning down to reveal the level

### ISSUE THREAD

**Issue by LachlanRMMorrow** [LachlanRMMorrow/Bullet-Ballet-Unity-Project#29]
## Bug occurring in Editor. Not Tested in Build.

**Expected Result:** _When the level starts, the camera should pan down and reveal the level. Once this is finished the player should be able to begin playing._

**Actual Result:** _When the level starts, the camera pans down to reveal the level. However the player is able to choose a weapon and start playing before the camera has finished panning._

**Comment by jamesy012** [comment]
Should be fixed in my next push.

It also wont move the camera until a weapon is selected

**Comment by LachlanRMMorrow** [comment]
Fixed. Thanks James.
