### ISSUE TITLE
Player's bullets spawning in wrong location.

### ISSUE THREAD

**Issue by JCRendingRaven** [LachlanRMMorrow/Bullet-Ballet-Unity-Project#30]
## Bug occurring in Editor. Not Tested in Build.

**Expected Result:** _Player bullets are spawn in front of the gun._

**Actual Result:** _Player bullets are spawning outside the game environment._

**Comment by LachlanRMMorrow** [comment]
Only seems to be occurring in certain levels. Probably an issue with transforms not being set to the right place.

**Comment by jamesy012** [comment]
It only spawns bullets if you pick the Beretta M9, transforms are fine. the scene where this is happening is Scenes\CURRENTLY USED LEVELS\Sprint 3 Prototypes\Dimitri's New Levels\For Revision\Cabin_Inside 1.unity.

There are also two players in the scene

**Comment by LachlanRMMorrow** [comment]
Seems to be fixed.
