### ISSUE TITLE
Upon entering a room in bullet time no enemies appear.

### ISSUE THREAD

**Issue by JCRendingRaven** [LachlanRMMorrow/Bullet-Ballet-Unity-Project#34]
## Bug occurring in Editor. Not Tested in Build.

**Expected Result:** _Upon entering a room with hidden enemies in bullet time the enemies should appear in the room._

**Actual Result:** _Upon entering a room in bullet time no enemies appear._

**Comment by LachlanRMMorrow** [comment]
Can you give an example of a level where this is happening @JCRendingRaven?

**Comment by jamesy012** [comment]
Yeah an example would be great

**Comment by LachlanRMMorrow** [comment]
Since no one has quoted an example and I've never seen this happen I'm going to close it.
