### ISSUE TITLE
Aiming with both weapons sometimes seemed to confuse the shooter. The arms would face backwards and cross over at times.

### ISSUE THREAD

**Issue by JCRendingRaven** [LachlanRMMorrow/Bullet-Ballet-Unity-Project#36]
## Bug occurring in Build.

**Expected Result:** _Aiming with both sticks points both weapons in the desired direction._

**Actual Result:** _Aiming with both weapons sometimes seemed to confuse the player character. The arms would face backwards and cross over at times._

**Comment by LachlanRMMorrow** [comment]
This is pretty much a rewording of an issue we've already got logged, so I'm just gonna close this one.
