### ISSUE TITLE
Going into one room and back into the other removes lighting from both and turns enemies invisible.

### ISSUE THREAD

**Issue by JCRendingRaven** [LachlanRMMorrow/Bullet-Ballet-Unity-Project#37]
## Bug occurring in Build.

**Expected Result:** _Going into one room and back into the other keeps lighting on and doesn't vanish enemies._

**Actual Result:** _Going into one room and back into the other removes lighting from both and turns enemies invisible._

**Comment by LachlanRMMorrow** [comment]
This is tied to the fog of war system still being pretty buggy. I'm going to make a Trello card for fixing up all the bugs for the fog of war system and link this to it along with the other related bugs that have been logged.
