### ISSUE TITLE
Got stuck on black screen after dying in level 2.

### ISSUE THREAD

**Issue by JCRendingRaven** [LachlanRMMorrow/Bullet-Ballet-Unity-Project#38]
## Bug occurring in Build.

**Expected Result:** _Game over menu should appear after dying on level 2._

**Actual Result:** _Got stuck on black screen after dying in level 2._

**Comment by JCRendingRaven** [comment]
Jack Wilson said it happens when you are using the m1911

**Comment by AddisonStewart** [comment]
Fixed
