### ISSUE TITLE
You can get shot on level 4 when hiding behind the pillars closest to the entry door

### ISSUE THREAD

**Issue by JCRendingRaven** [LachlanRMMorrow/Bullet-Ballet-Unity-Project#39]
## Bug occurring in Build.

**Expected Result:** _Pillars closest to the entry doors should provide cover fro bullets._

**Actual Result:** _You can get shot on level 4 when hiding behind the pillars closest to the entry door._

**Comment by jamesy012** [comment]
They are not the correct pillars

**Comment by LachlanRMMorrow** [comment]
Replaced them with the right ones and that fixed it.
