### ISSUE TITLE
Slow Motion sounds seems to be playing in the wrong order and not at the right time

### ISSUE THREAD

**Issue by LachlanRMMorrow** [LachlanRMMorrow/Bullet-Ballet-Unity-Project#4]
## Bug occurring in Editor. Not Tested in Build.

**Expected Result:** _Slow motion start sound should only play when slow motion starts. Slow motion end sound should only play when slow motion ends._

**Actual Result:** _Both sounds seem to sometimes play at random times for no reason or play in the wrong order, or not at all._

**Comment by LachlanRMMorrow** [comment]
Resolved part of this on my end. Made a much shorter version of the slow motion ending clip. Sounds a lot better now.

**Comment by jamesy012** [comment]
So this is closed?

**Comment by LachlanRMMorrow** [comment]
Sort of. They're playing in the right order now but they're not triggering on bullet time toggle, only when toggling pathing/planning mode.

**Comment by LachlanRMMorrow** [comment]
Issue Fixed. Good job James.
