### ISSUE TITLE
Player should not be able to go out of bounds on level 1 but can.

### ISSUE THREAD

**Issue by JCRendingRaven** [LachlanRMMorrow/Bullet-Ballet-Unity-Project#41]
## Bug occurring in Build.

**Expected Result:** _Player should not be able to go out of bounds on level 1._

**Actual Result:** _"At the end of the tutorial before i killed everyone, once i got to the end and looked straight ahead, when i went into the pathing mechanic i was able to get it out of the map and was not able to get it back in"mitchell johnson"._

**Comment by LachlanRMMorrow** [comment]
Think this is fixed.
