### ISSUE TITLE
Aiming with the analogue sticks needs to sped up to remove the disconnecting feel.

### ISSUE THREAD

**Issue by intelgen** [LachlanRMMorrow/Bullet-Ballet-Unity-Project#48]
## Bug occurring in Editor. Not tested in Build.

**Expected Result:** _Arms/aiming follows what you are physically doing with your hands on the analogue sticks and keeps good feel & flow._

**Actual Result:** _Aiming speed is too slow and creates a frustrating feel when trying to aim quickly at different directions. It needs to be sped up by a factor of at lest 3 - 4_

**Comment by LachlanRMMorrow** [comment]
Modified the speed by 1.5x. I'm pretty happy with how fast it is right now.
