### ISSUE TITLE
Dash/rolling needs some speed and blending tweaks.

### ISSUE THREAD

**Issue by intelgen** [LachlanRMMorrow/Bullet-Ballet-Unity-Project#49]
## Bug occurring in Editor. Not tested in Build.

**Expected Result:** _Animation is too slow and the blending is iffy._

**Actual Result:** _Dash/rolling speed needs to be increased as it is not realistic and looks as though it is in slow motion when it is not. The dash animation needs some blending tweaks & blending added at the end._

**Comment by jamesy012** [comment]
Speed of the animation is now affected by the time it takes to dash

**Comment by LachlanRMMorrow** [comment]
Pretty happy with how this looks now. Closing the issue.
